stages:
  data_ingestion:
    cmd: python src/ypd/pipeline/stage_01_data_ingestion.py
    deps:
      - src/ypd/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/yoga-poses-dataset

  prepare_base_model:
    cmd: python src/ypd/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/ypd/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - CLASSES
      - IMAGE_SIZE
      - PRETRAINED
    outs:
     - artifacts/prepare_base_model

  model_training:
    # code to run the specific pipeline
    cmd: python src/ypd/pipeline/stage_03_model_training.py
    # dependencies
    deps:
      - src/ypd/pipeline/stage_03_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/yoga-poses-dataset
      - artifacts/prepare_base_model
    # parameter dependencies
    params:
     - AUGMENTATION
     - IMAGE_SIZE
     - BATCH_SIZE
     - EPOCHS
     - LEARNING_RATE
    # outputs
    outs:
     - artifacts/training/resnet_model.pth