artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://www.kaggle.com/datasets/niharika41298/yoga-poses-dataset


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  resnet_base_model_path: artifacts/prepare_base_model/resnet_base_model.pth
  resnet_updated_base_model_path: artifacts/prepare_base_model/resnet_updated_base_model.pth